#!/bin/bash
################################################################################
# Camunda Platform - Automated Cleanup and Maintenance Script
#
# Purpose: Periodic cleanup to prevent disk space exhaustion
# Recommended: Run daily via cron (e.g., crontab -e: 0 2 * * * /path/to/script)
#
# Author: Generated by Claude Code
# Date: 2025-11-03
################################################################################

set -euo pipefail

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
LOG_FILE="/var/log/camunda-cleanup.log"
MAX_HEAPDUMP_AGE_DAYS=7
MAX_DOCKER_LOG_AGE_DAYS=30
CAMUNDA_URL="${CAMUNDA_URL:-http://localhost:8080}"
CAMUNDA_USER="${CAMUNDA_USER:-demo}"
CAMUNDA_PASSWORD="${CAMUNDA_PASSWORD:-demo}"

# Logging function
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

log_error() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: $*" | tee -a "$LOG_FILE" >&2
}

# Check if running as root (needed for some operations)
check_permissions() {
    if [[ $EUID -ne 0 ]] && [[ "$1" == "full" ]]; then
        log_error "Full cleanup requires root privileges. Run with sudo or as root."
        exit 1
    fi
}

################################################################################
# 1. Clean old heap dumps
################################################################################
cleanup_heapdumps() {
    log "=== Cleaning old heap dumps ==="

    # Find heap dump volume
    HEAPDUMP_VOLUME=$(docker volume inspect camunda-platform-standalone_camunda_heapdumps --format '{{ .Mountpoint }}' 2>/dev/null || echo "")

    if [[ -z "$HEAPDUMP_VOLUME" ]]; then
        log "Heap dump volume not found, skipping..."
        return
    fi

    # Count files before
    BEFORE_COUNT=$(find "$HEAPDUMP_VOLUME" -name "*.hprof" -type f 2>/dev/null | wc -l || echo 0)
    BEFORE_SIZE=$(du -sh "$HEAPDUMP_VOLUME" 2>/dev/null | cut -f1 || echo "0")

    # Remove heap dumps older than MAX_HEAPDUMP_AGE_DAYS
    if [[ $BEFORE_COUNT -gt 0 ]]; then
        find "$HEAPDUMP_VOLUME" -name "*.hprof" -type f -mtime +${MAX_HEAPDUMP_AGE_DAYS} -delete 2>/dev/null || true

        # Count files after
        AFTER_COUNT=$(find "$HEAPDUMP_VOLUME" -name "*.hprof" -type f 2>/dev/null | wc -l || echo 0)
        AFTER_SIZE=$(du -sh "$HEAPDUMP_VOLUME" 2>/dev/null | cut -f1 || echo "0")

        log "Heap dumps cleaned: ${BEFORE_COUNT} -> ${AFTER_COUNT} files | Size: ${BEFORE_SIZE} -> ${AFTER_SIZE}"
    else
        log "No heap dumps found"
    fi
}

################################################################################
# 2. Clean Camunda historical data
################################################################################
cleanup_camunda_history() {
    log "=== Cleaning Camunda historical data ==="

    # Get counts before cleanup
    RUNNING_BEFORE=$(curl -s -u "${CAMUNDA_USER}:${CAMUNDA_PASSWORD}" \
        "${CAMUNDA_URL}/engine-rest/process-instance/count" 2>/dev/null | \
        grep -o '"count":[0-9]*' | cut -d':' -f2 || echo "0")

    HISTORY_BEFORE=$(curl -s -u "${CAMUNDA_USER}:${CAMUNDA_PASSWORD}" \
        "${CAMUNDA_URL}/engine-rest/history/process-instance/count" 2>/dev/null | \
        grep -o '"count":[0-9]*' | cut -d':' -f2 || echo "0")

    log "Before cleanup - Running: ${RUNNING_BEFORE}, Historical: ${HISTORY_BEFORE}"

    # Trigger Camunda's built-in history cleanup job
    CLEANUP_RESULT=$(curl -s -X POST -u "${CAMUNDA_USER}:${CAMUNDA_PASSWORD}" \
        "${CAMUNDA_URL}/engine-rest/history/cleanup/execute" \
        -H "Content-Type: application/json" 2>/dev/null || echo "")

    if [[ -n "$CLEANUP_RESULT" ]]; then
        log "History cleanup job triggered successfully"

        # Wait for cleanup to complete (max 60 seconds)
        sleep 60

        # Get counts after cleanup
        HISTORY_AFTER=$(curl -s -u "${CAMUNDA_USER}:${CAMUNDA_PASSWORD}" \
            "${CAMUNDA_URL}/engine-rest/history/process-instance/count" 2>/dev/null | \
            grep -o '"count":[0-9]*' | cut -d':' -f2 || echo "0")

        CLEANED=$((HISTORY_BEFORE - HISTORY_AFTER))
        log "Historical instances cleaned: ${CLEANED} (${HISTORY_BEFORE} -> ${HISTORY_AFTER})"
    else
        log "Could not trigger history cleanup - Camunda may be unreachable"
    fi
}

################################################################################
# 3. Clean Docker system resources
################################################################################
cleanup_docker_system() {
    log "=== Cleaning Docker system resources ==="

    # Get disk usage before
    BEFORE_DOCKER=$(docker system df -v 2>/dev/null | grep "Local Volumes" | awk '{print $3}' || echo "0")

    # Remove unused Docker resources (but keep volumes and running containers)
    docker system prune -f --filter "until=${MAX_DOCKER_LOG_AGE_DAYS}d" 2>/dev/null || true

    # Get disk usage after
    AFTER_DOCKER=$(docker system df -v 2>/dev/null | grep "Local Volumes" | awk '{print $3}' || echo "0")

    log "Docker cleanup completed - Before: ${BEFORE_DOCKER}, After: ${AFTER_DOCKER}"
}

################################################################################
# 4. Vacuum PostgreSQL database
################################################################################
vacuum_database() {
    log "=== Running PostgreSQL VACUUM ==="

    # Find PostgreSQL container
    DB_CONTAINER=$(docker ps --filter "name=.*db.*" --filter "ancestor=postgres:16.3" --format "{{.ID}}" | head -1)

    if [[ -z "$DB_CONTAINER" ]]; then
        log "PostgreSQL container not found, skipping vacuum..."
        return
    fi

    # Run VACUUM ANALYZE on Camunda database
    docker exec "$DB_CONTAINER" psql -U camunda -d camunda -c "VACUUM ANALYZE;" 2>/dev/null || true

    # Get database size
    DB_SIZE=$(docker exec "$DB_CONTAINER" psql -U camunda -d camunda -t -c \
        "SELECT pg_size_pretty(pg_database_size('camunda'));" 2>/dev/null | xargs || echo "Unknown")

    log "Database vacuumed successfully - Current size: ${DB_SIZE}"
}

################################################################################
# 5. Generate disk usage report
################################################################################
generate_report() {
    log "=== Disk Usage Report ==="

    # Overall disk usage
    DISK_USAGE=$(df -h / | tail -1 | awk '{print "Used: " $3 " / " $2 " (" $5 ")"}')
    log "System disk: ${DISK_USAGE}"

    # Docker volumes
    log "Docker volumes:"
    docker volume ls --format "table {{.Name}}\t{{.Driver}}\t{{.Mountpoint}}" 2>/dev/null | grep camunda || true

    # Container sizes
    log "Container disk usage:"
    docker ps --format "table {{.Names}}\t{{.Size}}" 2>/dev/null | grep -E "(camunda|prometheus|grafana|postgres)" || true

    # Prometheus data size
    PROM_SIZE=$(docker volume inspect camunda-platform-standalone_prometheus_data --format '{{ .Mountpoint }}' 2>/dev/null | \
        xargs du -sh 2>/dev/null | cut -f1 || echo "Unknown")
    log "Prometheus data: ${PROM_SIZE}"

    # Grafana data size
    GRAFANA_SIZE=$(docker volume inspect camunda-platform-standalone_grafana_data --format '{{ .Mountpoint }}' 2>/dev/null | \
        xargs du -sh 2>/dev/null | cut -f1 || echo "Unknown")
    log "Grafana data: ${GRAFANA_SIZE}"
}

################################################################################
# Main execution
################################################################################
main() {
    local MODE="${1:-standard}"

    log "=========================================="
    log "Camunda Cleanup Script - Mode: ${MODE}"
    log "=========================================="

    case "$MODE" in
        standard)
            cleanup_camunda_history
            cleanup_heapdumps
            generate_report
            ;;
        full)
            check_permissions "full"
            cleanup_camunda_history
            cleanup_heapdumps
            cleanup_docker_system
            vacuum_database
            generate_report
            ;;
        report)
            generate_report
            ;;
        *)
            log_error "Invalid mode: $MODE"
            echo "Usage: $0 [standard|full|report]"
            echo "  standard - Clean Camunda history and heap dumps (default)"
            echo "  full     - Full cleanup including Docker system (requires root)"
            echo "  report   - Generate disk usage report only"
            exit 1
            ;;
    esac

    log "Cleanup completed successfully"
}

# Run main function with arguments
main "$@"
