#!/bin/bash
################################################################################
# Camunda Admin User Initialization Script
#
# Purpose: Ensure admin user exists in database on every startup
# This script creates or updates the admin user with correct credentials
#
# Author: Generated by Claude Code
# Date: 2025-11-03
################################################################################

set -euo pipefail

# Configuration from environment variables
ADMIN_USER="${CAMUNDA_BPM_ADMIN_USER:-admin}"
ADMIN_PASSWORD="${CAMUNDA_BPM_ADMIN_PASSWORD:-DiasCosta@!!2025}"
DB_CONTAINER="${DB_CONTAINER:-camunda-platform-db-1}"
DB_USER="${POSTGRES_USER:-camunda}"
DB_NAME="${POSTGRES_DB:-camunda}"

# Logging
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}

log_error() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: $*" >&2
}

# Wait for database to be ready
wait_for_db() {
    log "Waiting for database to be ready..."
    local max_attempts=30
    local attempt=1

    while [ $attempt -le $max_attempts ]; do
        if docker exec "$DB_CONTAINER" pg_isready -U "$DB_USER" -d "$DB_NAME" >/dev/null 2>&1; then
            log "Database is ready"
            return 0
        fi
        log "Attempt $attempt/$max_attempts: Database not ready yet..."
        sleep 2
        attempt=$((attempt + 1))
    done

    log_error "Database did not become ready in time"
    return 1
}

# Wait for Camunda to be ready
wait_for_camunda() {
    log "Waiting for Camunda to be ready..."
    local max_attempts=60
    local attempt=1

    while [ $attempt -le $max_attempts ]; do
        if curl -s http://localhost:8080/engine-rest/version >/dev/null 2>&1; then
            log "Camunda is ready"
            return 0
        fi
        log "Attempt $attempt/$max_attempts: Camunda not ready yet..."
        sleep 2
        attempt=$((attempt + 1))
    done

    log_error "Camunda did not become ready in time"
    return 1
}

# Create or update admin user
create_admin_user() {
    log "Creating/updating admin user: $ADMIN_USER"

    # Note: Camunda BPM Run auto-creates admin user from config on first startup
    # This script is a fallback for existing databases

    docker exec "$DB_CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" << EOF || log "Admin user creation skipped (may already exist or be managed by Camunda)"
-- Check if admin user exists
DO \$\$
BEGIN
    -- If user doesn't exist, Camunda will create it from config
    -- This is just a safety check and manual creation if needed

    IF NOT EXISTS (SELECT 1 FROM act_id_user WHERE id_ = '$ADMIN_USER') THEN
        RAISE NOTICE 'Admin user does not exist yet - Camunda will create it';
    ELSE
        RAISE NOTICE 'Admin user already exists: $ADMIN_USER';
    END IF;

    -- Ensure camunda-admin group exists
    IF NOT EXISTS (SELECT 1 FROM act_id_group WHERE id_ = 'camunda-admin') THEN
        INSERT INTO act_id_group (id_, rev_, name_, type_)
        VALUES ('camunda-admin', 1, 'camunda BPM Administrators', 'SYSTEM');
        RAISE NOTICE 'Created camunda-admin group';
    END IF;

    -- Ensure admin is member of camunda-admin group
    IF EXISTS (SELECT 1 FROM act_id_user WHERE id_ = '$ADMIN_USER') THEN
        IF NOT EXISTS (SELECT 1 FROM act_id_membership WHERE user_id_ = '$ADMIN_USER' AND group_id_ = 'camunda-admin') THEN
            INSERT INTO act_id_membership (user_id_, group_id_)
            VALUES ('$ADMIN_USER', 'camunda-admin');
            RAISE NOTICE 'Added $ADMIN_USER to camunda-admin group';
        END IF;
    END IF;

    -- Unlock user if locked
    UPDATE act_id_user SET lock_exp_time_ = NULL WHERE id_ = '$ADMIN_USER';
END \$\$;
EOF

    log "Admin user initialization completed"
}

# Main execution
main() {
    log "=========================================="
    log "Camunda Admin User Initialization"
    log "=========================================="
    log "Admin User: $ADMIN_USER"
    log "Database Container: $DB_CONTAINER"

    # Wait for services
    wait_for_db || exit 1
    wait_for_camunda || log "Warning: Camunda not responding yet (may still be starting)"

    # Create/update admin user
    create_admin_user

    log "Initialization completed successfully"
}

# Run only if database container exists
if docker ps --format '{{.Names}}' | grep -q "^${DB_CONTAINER}$"; then
    main "$@"
else
    log "Database container not found - skipping (may be using external database)"
    exit 0
fi
